import type { NextPage } from 'next'
import Head from 'next/head'

import { BackButtonItem } from '@/components/ui/BackButtonItem'

const AvatarEditPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>DEV-PFPLAY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray50 mx-[120px] pt-[46px] px-[60px] pb-[60px]">
        <BackButtonItem title="뭘 입고 놀아볼까요?" />
        <div className="flex gap-[30px]">
          <div className="bg-[#000] min-w-[400px] h-[620px]">AvatarBox</div>
          <div className="flex-col w-[100%]">
            <ul className="flex flex-wrap text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:border-gray-700 dark:text-gray-400 mb-[28px]">
              <li className="mr-2">
                <a
                  href="#"
                  aria-current="page"
                  className="inline-block p-4 text-red rounded-t-lg hover:text-gray-600 ">
                  Body
                </a>
              </li>
              <li className="mr-2">
                <a href="#" className="inline-block p-4 rounded-t-lg hover:text-gray-600 ">
                  Face
                </a>
              </li>
            </ul>
            <div className="flex gap-5 flex-wrap h-[480px] overflow-auto mb-4">
              {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11].map(value => (
                <div key={value} className="w-[200px] h-[200px] bg-[#1A1A1A]">
                  value
                </div>
              ))}
            </div>
            <button className="w-[280px] py-3 px-4 bg-redGradientStart text-white rounded-sm">
              Let&apos;s get in
            </button>
          </div>
        </div>
      </div>
    </>
  )
}
export default AvatarEditPage
