import { Header } from '@components/Header';
import { BackButtonItem } from '@components/ui/BackButtonItem';
import { ArrowLeft } from '@components/ui/icon/ArrowLeft';
import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';
import Head from 'next/head';

const ProfileEditPage: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>DEV-PFPLAY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="w-full h-[60px]" />
      <main className="px-[120px] mw-[1680px] h-[600px]">
        <BackButtonItem title="당신은 누구신가요?" />
        <div className="flex flex-col items-center justify-center h-full">
          <div className="flex gap-10 mb-[76px] items-center">
            <p className="text-white">닉네임*</p>
            <input className="w-[536px] border border-solid border-[#2F2F2F] bg-[#2F2F2F] rounded h-12" />
          </div>
          <div className="flex gap-[65px] items-center">
            <p className="text-white">소개</p>
            <input className="w-[536px] border border-solid border-[#2F2F2F] bg-[#2F2F2F] rounded h-12" />
          </div>
        </div>
      </main>
    </>
  );
};
export default ProfileEditPage;
