import AvatarBody from '@components/avatarBody';
import AvatarFace from '@components/avatarFace';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';

const Avatar: NextPage = () => {
  const [currentTab, setCurrentTab] = useState(1);

  const selectMenuHandler = (index: any) => {
    setCurrentTab(index);
  };

  const menuArr = [
    {
      name: 'Body',
      content: <AvatarBody />,
    },
    {
      name: 'Face',
      content: <AvatarFace />,
    },
  ];

  return (
    <>
      <Head>
        <title>DEV-PFPLAY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className=" bg-black fixed w-screen h-screen"
        style={{
          zIndex: -1,
        }}
      >
        <Image src="/image/Onboard.png" alt="Onboard" layout="fill" />
      </div>

      <header className="text-white flex justify-between items-center" style={{ height: '100px', maxWidth: '1680px', margin: '0 auto' }}>
        <Link href="/">
          <button>
            <Image src="/icons/wordmark_medium_white.png" alt="wordmark" width="150px" height="36px" style={{ marginTop: '1px' }} />
          </button>
        </Link>

        <div className="flex items-center">
          <div style={{ height: '36px', border: 'solid 1px #545454', borderRadius: '4px' }} className=" text-sm flex justify-center items-center px-6">
            <p className="mb-1">pfplay@gmail.com</p>
          </div>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-10 h-10 ml-7">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 017.843 4.582M12 3a8.997 8.997 0 00-7.843 4.582m15.686 0A11.953 11.953 0 0112 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0121 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0112 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 013 12c0-1.605.42-3.113 1.157-4.418"
            />
          </svg>
        </div>
      </header>
      <div className="w-full" style={{ height: '60px' }} />
      <main className="block text-white gap-6 " style={{ margin: '0 auto', maxWidth: '1680px', maxHeight: '800px', padding: '46px 60px' }}>
        <div className="text-2xl flex items-center mb-8 w-full">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8 cursor-pointer mr-5 mb-2">
            <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
          </svg>
          <p>뭘 입고 놀아볼까요?</p>
        </div>
        <div className="flex justify-between">
          <span className="mr-5 w-full" style={{ maxWidth: '400px', maxHeight: '620px' }}>
            <div style={{ height: '620px' }} className="bg-gray-500 w-full"></div>
          </span>
          <span className=" h-full w-full" style={{ maxWidth: '1100px' }}>
            <nav className="flex flex-col sm:flex-row">
              {menuArr.map((ele, index) => {
                return (
                  <button
                    key={index}
                    className={
                      currentTab === index
                        ? ' py-2 px-6 block text-xl font-bold hover:text-red-600 action:outline-none border-b-2 border-red-600 text-red-600'
                        : 'text-gray-200 py-2 px-6 block text-xl font-bold hover:text-red-600'
                    }
                    onClick={() => selectMenuHandler(index)}
                  >
                    {ele.name}
                  </button>
                );
              })}
            </nav>
            {menuArr[currentTab].content}
          </span>
        </div>
        <button
          className="flex items-center justify-center float-right mt-5"
          style={{ width: '280px', height: '48px', background: 'linear-gradient(97.75deg, #780808 -5.43%, #AE001F 97.56%)', borderRadius: '4px' }}
        >
          <p>Lef&apos;s get in</p>
        </button>
      </main>
    </>
  );
};
export default Avatar;
