import '@/styles/globals.css'

import { Metadata } from 'next'
import React from 'react'

import { Header } from '@/components/header'
import { Providers } from '@/components/providers'

export const metadata: Metadata = {
  title: 'PFPlay',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <div className="min-h-screen bg-onboarding bg-cover">{children}</div>
        </Providers>
      </body>
    </html>
  )
}
