import { Metadata } from 'next';
import Image from 'next/image';
import HomeLoginButton from '@/components/@features/Home/HomeLoginButton';

export const metadata: Metadata = {
  title: 'PFPlay',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

const HomePage = () => {
  return (
    <>
      <main className='flexColCenter  bg-onboarding'>
        <Image
          className='mb-[72px]'
          src='/logos/wordmark_medium_white.svg'
          width={297.24}
          height={72}
          alt='logo'
        />
        <HomeLoginButton />
      </main>
      <footer className='w-full absolute bottom-[68px] flexRow justify-between text-white px-[120px]'>
        <p className='footerText'>Privacy&Terms</p>
        <p className='footerText'>당신의 PFP는 안녕하신가요?</p>
      </footer>
    </>
  );
};

export default HomePage;
