import { APP_NAME, generateMetaData } from '@/utils/routes/generateMetaData';
import { generatePaths } from '@/utils/routes/generatePaths';

const TEMP_DESCRIPTION = '';

const routes = {
  HOME: {
    index: { route: '/', title: APP_NAME, description: 'Generated by create next app' },
  },
  AUTH: {
    group: true,
    SIGN_IN: {
      index: { route: 'sign-in', title: 'Sign In', description: TEMP_DESCRIPTION },
    },
  },
  PARTIES: {
    index: { route: 'parties', title: 'Parties', description: TEMP_DESCRIPTION },
    room: { route: 'room/[id]', title: 'Party Room', description: TEMP_DESCRIPTION },
  },
  SETTINGS: {
    group: 'settings',
    AVATAR: {
      index: { route: 'avatar', title: 'Avatar Settings', description: TEMP_DESCRIPTION },
    },
    PROFILE: {
      index: { route: 'profile', title: 'Profile Settings', description: TEMP_DESCRIPTION },
    },
  },
} as const;

/**
 * ```
 * ** ----- Dynamic Example ----- **
 * const authRoutes = {
 *   ...
 *   PARENT: {
 *     index: { route: 'abc', title: 'ABC' }
 *     detail: { route: 'detail/[userId]', title: 'ABC Detail' },
 *   },
 * }
 * ...
 * router.push(replaceDynamic(
 *   ROUTES.PARENT.detail.route,
 *   { userId: 1000 }
 * ))
 * ** --------------------------- **
 * ```
 */
export const ROUTES = generatePaths(routes);
export const PAGE_METADATA = generateMetaData(routes);
