/* eslint-disable prettier/prettier */
import { yupResolver } from '@hookform/resolvers/yup'
import type { NextPage } from 'next'
import Image from 'next/future/image'
import Head from 'next/head'
import { useCallback, useState } from 'react'
import { useForm } from 'react-hook-form'

import { Header } from '@/components/Header'
import { MyPlayListModal } from '@/components/modal/MyPlayListModal'
import { MyProfileModal } from '@/components/modal/MyProflieModal'
import { SubParty } from '@/components/partylist/subparty' 



const PartyListPage: NextPage = () => {

  const [isListOpen,setIsListOpen] = useState(false)
  const [isProfileOpen,setIsProfileOpen] = useState(false)

  const handleOpenListModal = useCallback(() => setIsListOpen(!isListOpen), [isListOpen])
  const handleOpenProfileModal = useCallback(() => setIsProfileOpen(!isProfileOpen),[isProfileOpen])



  return (
   <>
      <div>
        <MyProfileModal isOpen={isProfileOpen} onClose={handleOpenProfileModal} />
        <MyPlayListModal isOpen={isListOpen} onClose={handleOpenListModal} />
        {/*백그라운드 이미지 삭제*/}
        <div className="bg-[#000000] fixed w-screen h-screen" style={{ zIndex: -1 }}></div>
        <Head>
          <title>DEV-PFPLAY</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <div className="grid grid-rows-3 grid-flow-col">
          {/* 사이드바 */}
          <div className="row-span-3 flex flex-col justify-center">
            <div className="ml-3">
              <div className="bg-[#111111] flex flex-col ml-10">
                <div className="mt-10 mb-5 flex flex-col items-center">
                  <Image
                    className="mt-4 mx-[5px] rounded-full"
                    onClick={handleOpenProfileModal}
                    src="/image/Ellipse 26.png"
                    alt="person"
                    width={48}
                    height={48}></Image>
                  <p className="mt-3 text-[#DADADA] text-[10px]">내 프로필</p>
                </div>
                <div className="mb-10 mt-5 flex flex-col items-center">
                  <Image
                    className="mt-4 mx-[5px] rounded-full"
                    onClick={handleOpenListModal}
                    src="/image/vector.png"
                    alt="person"
                    width={48}
                    height={48}></Image>
                  <p className="mt-3 text-[#DADADA] text-[10px]">플레이리스트</p>
                </div>
              </div>
            </div>
          </div>
          {/* 메인 스테이지 */}
          <div
            className="col-span-2 flex justify-between items-center pt-10 px-[115px]"
            style={{ maxWidth: '1640px' }}>
            <div className="flex-auto mt-10 mx-[120px] bg-[url('/image/PartyRoom.png')] bg_blur">
              <div className="px-4 py-5 sm:px-6">
                <h3 className="text-lg font-medium leading-6 text-[#FDFDFD] z-[10]">
                  PFPlay Main Stage
                </h3>
                <p className="mt-1 max-w-2xl text-sm text-[#DADADA]">파티에 오신 것을 환영합니다</p>
              </div>
              <div className="grid grid-cols-12 gap-4 mt-10 ml-6 pb-5">
                <div className="col-span-1 text-[#FDFDFD] flex items-end">
                  <Image
                    className="mt-4"
                    src="/image/icn_person_outline.png"
                    alt="person"
                    width={16}
                    height={16}></Image>
                  <p className="text-[12px] pl-1">48</p>
                </div>
                <div className="col-span-2 text-[#FDFDFD] flex items-end justify-items-start">
                  <Image
                    className="mt-4 mx-[5px] rounded-full"
                    src="/image/user1.png"
                    alt="person"
                    width={24}
                    height={24}></Image>
                  <Image
                    className="mt-4 mx-[5px] rounded-full"
                    src="/image/user2.png"
                    alt="person"
                    width={24}
                    height={24}></Image>
                  <Image
                    className="mt-4 mx-[5px] rounded-full"
                    src="/image/user3.jfif"
                    alt="person"
                    width={24}
                    height={24}></Image>
                </div>
                <div className="col-span-9 text-[#FDFDFD] px-5">
                  <hr></hr>
                  <div className="flex items-center">
                    <div>
                      <Image
                        className="mt-4 rounded"
                        src="/image/newjeans.png"
                        alt="jeans"
                        width={100}
                        height={50}></Image>
                    </div>
                    <div className="mt-4 ml-5">
                      <p>NewJeans(뉴진스) Attention Official MV</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* 서브 스테이지 */}
          <div
            className="row-span-2 col-span-2 flex justify-between pt-5 px-[105px]"
            style={{ maxWidth: '1640px' }}>
            <div className="flex-auto mx-[120px]">
              <div className="grid grid-cols-9 gap-4 pt-2 pb-2">
                <div className="col-span-3 bg-[#111111] mx-[9px] flex bg_blur">
                  <div className="flex flex-col">
                    <div className="mt-3">
                      <h3 className="text-[#F31F2C] text-[30px] mx-[20px]">Be a PFPlay Host</h3>
                      <p className="text-[#DADADA] text-[14px] mx-[20px]">
                        원하는 테마의 파티를 자유롭게 호스트해보세요!
                      </p>
                    </div>
                    <div className="flex justify-center pt-3">
                      <Image
                        className=""
                        src="/image/icn_add.png"
                        alt="add"
                        width={80}
                        height={40}></Image>
                    </div>
                  </div>
                </div>
                <SubParty />
                <SubParty />
              </div>
              <div className="grid grid-cols-9 gap-4 pt-2 pb-2">
                <SubParty />
                <SubParty />
                <SubParty />
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
export default PartyListPage

