export enum QueryKeys {
  Me = 'me',
  AvatarBodies = 'avatar-bodies',
  AvatarFaces = 'avatar-faces',
  Nfts = 'nfts',
  PartyroomList = 'partyroom/list',
  Playlist = 'playlist',
  PlaylistTracks = 'playlist/tracks',
  Musics = 'musics',
  MyBlocks = 'my-blocks',
  DjingQueue = 'partyroom/djing-queue',
  Crews = 'partyroom/crews',
  PartyroomDetailSummary = 'partyroom/summary',
  PlaybackHistory = 'partyroom/playback-history',
  Penalties = 'partyroom/penalties',
}
