export const AVATAR_GROUP = {
  HEIGHT: 180,
  WIDTH: 135,
  COLLISION_RADIUS: 30, // forceCollide radius 값
} as const;

export const D3_OPTIONS_FOR_INITIAL_NODES = {
  MIN_DISTANCE: 30,
  CENTER_Y_OFFSET: 180,
  CENTER_X_OFFSET: 135,
  FORCE_STRENGTH: -10,
  COLLIDE_RADIUS: 30,
  MAX_ATTEMPTS: 100,
};

export const D3_OPTIONS_FOR_ADDED_NODES = {
  MIN_DISTANCE: 60,
  CENTER_Y_OFFSET: 360,
  CENTER_X_OFFSET: 270,
  FORCE_STRENGTH: -20,
  COLLIDE_RADIUS: 45,
  MAX_ATTEMPTS: 200,
};

export const OVAL_CONFIG = {
  CENTER_X_RATIO: 0.55,
  CENTER_Y_RATIO: 0.8,
  RADIUS_X_RATIO: 0.25,
  RADIUS_Y_RATIO: 0.25,
  FALLBACK_RADIUS_RATIO: 0.5,
  BOUNDARY_CONSTRAINT: 0.95,
  FORCE_X_STRENGTH: 0.05,
  FORCE_Y_STRENGTH: 0.1,
  SIMULATION_TICKS: 100,
} as const;
