export const AVATAR_GROUP = {
  HEIGHT: 180,
  WIDTH: 135,
  COLLISION_RADIUS: 30, // forceCollide radius 값
} as const;

export const D3_OPTIONS_FOR_INITIAL_NODES = {
  MIN_DISTANCE: 30,
  CENTER_Y_OFFSET: 180,
  CENTER_X_OFFSET: 135,
  FORCE_STRENGTH: -10,
  COLLIDE_RADIUS: 30,
  MAX_ATTEMPTS: 100,
};

export const D3_OPTIONS_FOR_ADDED_NODES = {
  MIN_DISTANCE: 60,
  CENTER_Y_OFFSET: 360,
  CENTER_X_OFFSET: 270,
  FORCE_STRENGTH: -20,
  COLLIDE_RADIUS: 45,
  MAX_ATTEMPTS: 200,
};

export type OvalConfig = {
  CENTER_X_RATIO: number;
  CENTER_Y_RATIO: number;
  RADIUS_X_RATIO: number;
  RADIUS_Y_RATIO: number;
  FALLBACK_RADIUS_RATIO: number;
  BOUNDARY_CONSTRAINT: number;
  FORCE_X_STRENGTH: number;
  FORCE_Y_STRENGTH: number;
  SIMULATION_TICKS: number;
};

/** 궁중(메인 무대) 클러스터 설정 */
export const OVAL_CONFIG_COURT: OvalConfig = {
  CENTER_X_RATIO: 0.55,
  CENTER_Y_RATIO: 0.8,
  RADIUS_X_RATIO: 0.25,
  RADIUS_Y_RATIO: 0.25,
  FALLBACK_RADIUS_RATIO: 0.5,
  BOUNDARY_CONSTRAINT: 0.95,
  FORCE_X_STRENGTH: 0.05,
  FORCE_Y_STRENGTH: 0.1,
  SIMULATION_TICKS: 100,
};

/** DJ 대기열 클러스터 설정 */
export const OVAL_CONFIG_QUEUE: OvalConfig = {
  CENTER_X_RATIO: 0.2,
  CENTER_Y_RATIO: 0.5,
  RADIUS_X_RATIO: 0.45,
  RADIUS_Y_RATIO: 0.2,
  FALLBACK_RADIUS_RATIO: 0.5,
  BOUNDARY_CONSTRAINT: 0.95,
  FORCE_X_STRENGTH: 0.05,
  FORCE_Y_STRENGTH: 0.1,
  SIMULATION_TICKS: 100,
};
