name: lint check

on: pull_request

jobs:
  eslint-test:
    name: eslint test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
      - run: npm i -g yarn@1.22.22
      - run: yarn
      - run: yarn lint
