name: lint check

on: pull_request

jobs:
  eslint-test:
    name: lint & i18n
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
      - run: npm i -g yarn@1.22.22
      - run: yarn
      - run: yarn lint
      - name: i18n sync check
        run: |
          yarn i18n
          git diff --exit-code src/shared/lib/localization/dictionaries
