name: vercel build check

on:
  pull_request:
    branches: [development, main]

jobs:
  build:
    name: vercel build
    runs-on: ubuntu-latest
    env:
      VERCEL_CLI_VERSION: 48.4.1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
      - name: Build
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx --yes vercel@${VERCEL_CLI_VERSION} build --yes --token=${{ secrets.VERCEL_TOKEN }}
