name: vercel preview

on:
  push:
    branches: [development]
  workflow_dispatch:

jobs:
  deploy:
    name: deploy preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel Preview
        id: deploy
        run: |
          URL=$(npx vercel deploy --scope dev-8226s-projects --yes --token=${{ secrets.VERCEL_TOKEN }})
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Alias Preview Domain
        run: |
          npx vercel alias set ${{ steps.deploy.outputs.url }} stg.pfplay.xyz --scope dev-8226s-projects --token=${{ secrets.VERCEL_TOKEN }}
